# Use a slim version of Python 3.11 as our base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Install system dependencies needed for psycopg2 (PostgreSQL adapter)
RUN apt-get update \ 
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install dependencies
# This step is cached, speeding up rebuilds if requirements.txt doesn't change
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# The command to run the application is defined in docker-compose.yml
# EXPOSE 8000