"""Create accountant_data table

Revision ID: 011e7a9789d6
Revises: 
Create Date: 2025-11-27 16:57:00.877180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011e7a9789d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountant_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('tax_liability', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('compliance_status', sa.String(), nullable=True),
    sa.Column('data_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('data_period_start', sa.DateTime(), nullable=True),
    sa.Column('data_period_end', sa.DateTime(), nullable=True),
    sa.Column('is_processed_by_ai', sa.Boolean(), nullable=True),
    sa.Column('ai_summary_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountant_data_agent_id'), 'accountant_data', ['agent_id'], unique=False)
    op.create_index(op.f('ix_accountant_data_client_name'), 'accountant_data', ['client_name'], unique=False)
    op.create_index(op.f('ix_accountant_data_id'), 'accountant_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accountant_data_id'), table_name='accountant_data')
    op.drop_index(op.f('ix_accountant_data_client_name'), table_name='accountant_data')
    op.drop_index(op.f('ix_accountant_data_agent_id'), table_name='accountant_data')
    op.drop_table('accountant_data')
    # ### end Alembic commands ###
