"""Add DataSummary table and update AccountantData

Revision ID: 45463d7da39f
Revises: 011e7a9789d6
Create Date: 2025-11-30 18:01:02.227843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45463d7da39f'
down_revision: Union[str, None] = '011e7a9789d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('summary_type', sa.String(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=False),
    sa.Column('source_data_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('llm_model_used', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_summaries_agent_id'), 'data_summaries', ['agent_id'], unique=False)
    op.create_index(op.f('ix_data_summaries_id'), 'data_summaries', ['id'], unique=False)
    op.add_column('accountant_data', sa.Column('raw_data_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountant_data', 'raw_data_payload')
    op.drop_index(op.f('ix_data_summaries_id'), table_name='data_summaries')
    op.drop_index(op.f('ix_data_summaries_agent_id'), table_name='data_summaries')
    op.drop_table('data_summaries')
    # ### end Alembic commands ###
